// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/exercises": {
            "get": {
                "description": "Возвращает список всех упражнений",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Получить все упражнения",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ExerciseResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/exercises/by-tags": {
            "post": {
                "description": "Возвращает список упражнений, связанных со всеми указанными тегами",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Получить упражнения по нескольким тегам",
                "parameters": [
                    {
                        "description": "Массив ID тегов",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.GetExercisesByMultipleTagsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ExerciseResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/exercises/search": {
            "get": {
                "description": "Возвращает список упражнений, соответствующих поисковому запросу и фильтрам",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Поиск упражнений",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поисковый запрос",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "ID тега для фильтрации",
                        "name": "tag_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Лимит результатов",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение для пагинации",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ExerciseResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/exercises/tag/{tag_id}": {
            "get": {
                "description": "Возвращает список упражнений, связанных с указанным тегом",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Получить упражнения по тегу",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Tag ID",
                        "name": "tag_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ExerciseResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/exercises/{exercise_id}/tags": {
            "get": {
                "description": "Возвращает список тегов, связанных с указанным упражнением",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Получить теги упражнения",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Exercise ID",
                        "name": "exercise_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TagResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/exercises/{id}": {
            "get": {
                "description": "Возвращает информацию об упражнении по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Получить упражнение по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Exercise ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ExerciseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tags": {
            "get": {
                "description": "Возвращает список всех тегов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Получить все теги",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TagResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tags/popular": {
            "get": {
                "description": "Возвращает список самых популярных тегов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Получить популярные теги",
                "parameters": [
                    {
                        "maximum": 50,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Лимит тегов",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TagResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tags/{id}": {
            "get": {
                "description": "Возвращает информацию о теге по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Получить тег по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TagResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/training-exercises": {
            "post": {
                "description": "Добавляет упражнение к существующей тренировке",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "training-exercises"
                ],
                "summary": "Добавить упражнение к тренировке",
                "parameters": [
                    {
                        "description": "Данные упражнения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.AddExerciseToTrainingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainedExerciseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет упражнение из тренировки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "training-exercises"
                ],
                "summary": "Удалить упражнение из тренировки",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Training ID",
                        "name": "training_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Exercise ID",
                        "name": "exercise_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/training-exercises/{id}": {
            "put": {
                "description": "Обновляет информацию о выполненном упражнении в тренировке",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "training-exercises"
                ],
                "summary": "Обновить выполненное упражнение",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Trained Exercise ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.UpdateTrainedExerciseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainedExerciseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/trainings": {
            "get": {
                "description": "Возвращает все тренировки указанного пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainings"
                ],
                "summary": "Получить тренировки пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainingResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новую тренировку для пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainings"
                ],
                "summary": "Создать тренировку",
                "parameters": [
                    {
                        "description": "Данные тренировки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.CreateTrainingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/trainings/stats": {
            "get": {
                "description": "Возвращает статистику тренировок пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainings"
                ],
                "summary": "Получить статистику тренировок",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainingStatsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/trainings/{id}": {
            "get": {
                "description": "Возвращает информацию о тренировке со списком упражнений",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainings"
                ],
                "summary": "Получить тренировку с упражнениями",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Training ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет информацию о тренировке",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainings"
                ],
                "summary": "Обновить тренировку",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Training ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.UpdateTrainingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет тренировку по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainings"
                ],
                "summary": "Удалить тренировку",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Training ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/trainings/{id}/complete": {
            "patch": {
                "description": "Отмечает тренировку как завершенную и устанавливает рейтинг",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainings"
                ],
                "summary": "Завершить тренировку",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Training ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для завершения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.CompleteTrainingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.AddExerciseToTrainingRequest": {
            "type": "object",
            "required": [
                "exercise_id",
                "training_id"
            ],
            "properties": {
                "approaches": {
                    "type": "integer",
                    "maximum": 20,
                    "minimum": 1,
                    "example": 3
                },
                "doing": {
                    "type": "string",
                    "example": "1h"
                },
                "exercise_id": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "notes": {
                    "type": "string",
                    "example": "Тяжело далось"
                },
                "reps": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1,
                    "example": 10
                },
                "rest": {
                    "type": "string",
                    "example": "30m"
                },
                "time": {
                    "type": "string",
                    "example": "1h30m"
                },
                "training_id": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "weight": {
                    "type": "number",
                    "maximum": 1000,
                    "minimum": 0,
                    "example": 50.5
                }
            }
        },
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.CompleteTrainingRequest": {
            "type": "object",
            "properties": {
                "rating": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 5
                }
            }
        },
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.CreateTrainingRequest": {
            "type": "object",
            "required": [
                "planned_date",
                "user_id"
            ],
            "properties": {
                "actual_date": {
                    "type": "string",
                    "example": "2023-10-05T16:30:00Z"
                },
                "finished_at": {
                    "type": "string",
                    "example": "2023-10-05T16:30:00Z"
                },
                "is_done": {
                    "type": "boolean",
                    "example": false
                },
                "planned_date": {
                    "type": "string",
                    "example": "2023-10-05T15:00:00Z"
                },
                "rating": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 5
                },
                "started_at": {
                    "type": "string",
                    "example": "2023-10-05T15:00:00Z"
                },
                "total_duration": {
                    "type": "string",
                    "example": "1h30m"
                },
                "total_exercise_time": {
                    "type": "string",
                    "example": "1h"
                },
                "total_rest_time": {
                    "type": "string",
                    "example": "30m"
                },
                "user_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.ExerciseResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Базовое упражнение для развития грудных мышц"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TagResponse"
                    }
                },
                "video_url": {
                    "type": "string",
                    "example": "https://example.com/video.mp4"
                }
            }
        },
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.GetExercisesByMultipleTagsRequest": {
            "type": "object"
        },
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TagResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "type": {
                    "type": "string",
                    "example": "силовое"
                }
            }
        },
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainedExerciseResponse": {
            "type": "object",
            "properties": {
                "approaches": {
                    "type": "integer",
                    "example": 3
                },
                "doing": {
                    "type": "string",
                    "example": "1h"
                },
                "exercise_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "notes": {
                    "type": "string",
                    "example": "Тяжело далось"
                },
                "reps": {
                    "type": "integer",
                    "example": 10
                },
                "rest": {
                    "type": "string",
                    "example": "30m"
                },
                "time": {
                    "type": "string",
                    "example": "1h30m"
                },
                "training_id": {
                    "type": "integer",
                    "example": 1
                },
                "weight": {
                    "type": "number",
                    "example": 50.5
                }
            }
        },
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainingResponse": {
            "type": "object",
            "properties": {
                "actual_date": {
                    "type": "string",
                    "example": "2023-10-05T16:30:00Z"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainedExerciseResponse"
                    }
                },
                "finished_at": {
                    "type": "string",
                    "example": "2023-10-05T16:30:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_done": {
                    "type": "boolean",
                    "example": true
                },
                "planned_date": {
                    "type": "string",
                    "example": "2023-10-05T15:00:00Z"
                },
                "rating": {
                    "type": "integer",
                    "example": 5
                },
                "started_at": {
                    "type": "string",
                    "example": "2023-10-05T15:00:00Z"
                },
                "total_duration": {
                    "type": "string",
                    "example": "1h30m"
                },
                "total_exercise_time": {
                    "type": "string",
                    "example": "1h"
                },
                "total_rest_time": {
                    "type": "string",
                    "example": "30m"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.TrainingStatsResponse": {
            "type": "object",
            "properties": {
                "average_rating": {
                    "type": "number",
                    "example": 4.5
                },
                "completed_trainings": {
                    "type": "integer",
                    "example": 12
                },
                "last_training_date": {
                    "type": "string",
                    "example": "2023-10-05T16:30:00Z"
                },
                "total_duration": {
                    "type": "string",
                    "example": "45h30m"
                },
                "total_trainings": {
                    "type": "integer",
                    "example": 15
                }
            }
        },
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.UpdateTrainedExerciseRequest": {
            "type": "object",
            "properties": {
                "approaches": {
                    "type": "integer",
                    "maximum": 20,
                    "minimum": 1,
                    "example": 4
                },
                "doing": {
                    "type": "string",
                    "example": "1h15m"
                },
                "notes": {
                    "type": "string",
                    "example": "Стало легче"
                },
                "reps": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1,
                    "example": 12
                },
                "rest": {
                    "type": "string",
                    "example": "30m"
                },
                "time": {
                    "type": "string",
                    "example": "1h45m"
                },
                "weight": {
                    "type": "number",
                    "maximum": 1000,
                    "minimum": 0,
                    "example": 55
                }
            }
        },
        "github_com_EnduranNSU_trainings_internal_adapter_in_http_dto.UpdateTrainingRequest": {
            "type": "object",
            "required": [
                "planned_date"
            ],
            "properties": {
                "actual_date": {
                    "type": "string",
                    "example": "2023-10-05T16:30:00Z"
                },
                "finished_at": {
                    "type": "string",
                    "example": "2023-10-05T16:30:00Z"
                },
                "is_done": {
                    "type": "boolean",
                    "example": true
                },
                "planned_date": {
                    "type": "string",
                    "example": "2023-10-05T15:00:00Z"
                },
                "rating": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 5
                },
                "started_at": {
                    "type": "string",
                    "example": "2023-10-05T15:00:00Z"
                },
                "total_duration": {
                    "type": "string",
                    "example": "1h30m"
                },
                "total_exercise_time": {
                    "type": "string",
                    "example": "1h"
                },
                "total_rest_time": {
                    "type": "string",
                    "example": "30m"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
